export default [
	{ id: "divide", code: "/" },
	{ id: "multiply", code: "*" },
	{ id: "add", code: "+" },
	{ id: "subtract", code: "-" },
	{ id: "seven", code: "7" },
	{ id: "eight", code: "8" },
	{ id: "nine", code: "9" },
	{ id: "clear", code: "c" },
	{ id: "four", code: "4" },
	{ id: "five", code: "5" },
	{ id: "six", code: "6" },
	{ id: "clear-all", code: "ce" },
	{ id: "one", code: "1" },
	{ id: "two", code: "2" },
	{ id: "three", code: "3" },
	{ id: "backspace", code: "<" },
	{ id: "zero", code: "0" },
	{ id: "decimal", code: "." },
	{ id: "equals", code: "=" }
];
